# Generated by Django 4.1.3 on 2022-11-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tempest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing_bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clothing_outer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='region',
            field=models.CharField(max_length=6),
        ),
        migrations.CreateModel(
            name='ClotheRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempest.clothing_bottom')),
                ('outer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempest.clothing_outer')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempest.clothing_top')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tempestuser')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempest.weather')),
            ],
        ),
    ]
