# Generated by Django 4.1.3 on 2022-11-16 09:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tempest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clotherecords',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='clotherecords',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='clotherecords',
            name='outer',
        ),
        migrations.RemoveField(
            model_name='clotherecords',
            name='top',
        ),
        migrations.AddField(
            model_name='clotherecords',
            name='clothes',
            field=jsonfield.fields.JSONField(default={'야채': '감자'}),
            preserve_default=False,
        ),
    ]
