# Generated by Django 4.1.3 on 2022-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempest', '0002_remove_clotherecords_bottom_remove_clotherecords_etc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing_bottom',
            name='img_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clothing_etc',
            name='img_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clothing_outer',
            name='img_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clothing_top',
            name='img_path',
            field=models.TextField(null=True),
        ),
    ]
