# Generated by Django 4.1.3 on 2022-11-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempest', '0003_remove_weather_content_weather_basetime_weather_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='baseDate',
            field=models.CharField(default=20220000, max_length=10),
            preserve_default=False,
        ),
    ]
