# Generated by Django 4.1.3 on 2022-11-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempest', '0005_clothing_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clotherecords',
            name='etc',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='tempest.clothing_etc'),
            preserve_default=False,
        ),
    ]
